// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkoaYxmQ5N-o8LzPQPNT2q2eZ2ewmv8rc',
    appId: '1:165338588203:web:4d6a7b4db9d7df3646b66e',
    messagingSenderId: '165338588203',
    projectId: 'roastedmoon',
    authDomain: 'roastedmoon.firebaseapp.com',
    storageBucket: 'roastedmoon.firebasestorage.app',
    measurementId: 'G-M8SNH2RJQD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSeEOB8uzoTYdVX3LgWpuLaMSGiobnPS4',
    appId: '1:165338588203:android:dd4dcb87c18a6acd46b66e',
    messagingSenderId: '165338588203',
    projectId: 'roastedmoon',
    storageBucket: 'roastedmoon.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLo9U20iSUsvhiTJOgSksV4lkiK_jyFBI',
    appId: '1:165338588203:ios:6e30ae682325edaa46b66e',
    messagingSenderId: '165338588203',
    projectId: 'roastedmoon',
    storageBucket: 'roastedmoon.firebasestorage.app',
    iosBundleId: 'com.roastedmoon.roastedmoonLegalease',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLo9U20iSUsvhiTJOgSksV4lkiK_jyFBI',
    appId: '1:165338588203:ios:6e30ae682325edaa46b66e',
    messagingSenderId: '165338588203',
    projectId: 'roastedmoon',
    storageBucket: 'roastedmoon.firebasestorage.app',
    iosBundleId: 'com.roastedmoon.roastedmoonLegalease',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkoaYxmQ5N-o8LzPQPNT2q2eZ2ewmv8rc',
    appId: '1:165338588203:web:8ea570d9a596f68a46b66e',
    messagingSenderId: '165338588203',
    projectId: 'roastedmoon',
    authDomain: 'roastedmoon.firebaseapp.com',
    storageBucket: 'roastedmoon.firebasestorage.app',
    measurementId: 'G-L008DMQHGY',
  );
}
